language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="ode:."
  matrix:
  - PACKAGE="ode" DISTRO="fedora-28" OCAML_VERSION="4.07"
  - PACKAGE="ode" DISTRO="ubuntu-18.04" OCAML_VERSION="4.07"
