language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="owl-ode:. owl-ode-sundials:."
  matrix:
  - PACKAGE="owl-ode" DISTRO="debian-stable" OCAML_VERSION="4.07"
  - PACKAGE="owl-ode-sundials" DISTRO="debian-stable" OCAML_VERSION="4.07"
